# -*- coding: utf-8 -*-
"""YOLOv3_colab_training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E2XH-dYpP3fCx-uclfFCaX_aRcJtRY73

========================================================<br>
<br>
   File name   : YOLOv3_colab_training.ipynb<br>
   Author      : PyLessons<br>
   Created date: 2020-05-26<br>
   Website     : https://pylessons.com/YOLOv3-TF2-GoogleColab<br>
   GitHub      : https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3<br>
   Description : Train custom model on Google colab tutorial<br>
<br>
================================================================


**Open this notebook from google drive**<br>
**Go to "Edit" -> "Notebook settings" and enable GPU.**
"""

# Check if NVIDIA GPU is enabled
!nvidia-smi

"""**Connect and authorize google drive with google colab:**"""

from google.colab import drive
drive.mount('/content/gdrive')
!ls

"""**Open our project "TensorFlow-2.x-YOLOv3" direcotry in google drive:**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/My\ Drive/etiquetas/yolov3/TensorFlow-2.x-YOLOv3
!ls

"""**Install all required libraries for our project:**"""

!pip install -r ./requirements.txt

"""**Download yolov3.weights if you don't have it:**"""

#!wget -P model_data https://pjreddie.com/media/files/yolov3.weights #já fiz download

"""**Test if TensorFlow works with gpu for you, in output should see similar results:**
```
2.2.0
'/device:GPU:0'
```
"""

import tensorflow as tf
print(tf.__version__)
tf.test.gpu_device_name()

"""**Test by loading trained model:**"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline  
import tensorflow as tf
from yolov3.yolov4 import Create_Yolo
from yolov3.utils import load_yolo_weights, detect_image
from yolov3.configs import *

if YOLO_TYPE == "yolov4":
    Darknet_weights = YOLO_V4_TINY_WEIGHTS if TRAIN_YOLO_TINY else YOLO_V4_WEIGHTS
if YOLO_TYPE == "yolov3":
    Darknet_weights = YOLO_V3_TINY_WEIGHTS if TRAIN_YOLO_TINY else YOLO_V3_WEIGHTS

yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE)
load_yolo_weights(yolo, Darknet_weights) # use Darknet weights

"""**Test by testing detection on original model:**"""

image_path   = "./IMAGES/etiqueta_3.jpg"

image = detect_image(yolo, image_path, '', input_size=YOLO_INPUT_SIZE, show=False, rectangle_colors=(255,0,0))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(30,15))
plt.imshow(image)

"""**Start training custom model:**"""

from train import *
tf.keras.backend.clear_session()
main()

# Commented out IPython magic to ensure Python compatibility.
# Load the TensorBoard notebook extension
# %load_ext tensorboard

import tensorflow as tf
import datetime, os

!kill 623

!ls "./log"

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir "./log"

"""**Create Yolo v3 custom model and load custom trained weights**"""

yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=TRAIN_CLASSES)
yolo.load_weights("./checkpoints/yolov3_custom") # use keras weights ### NOVO PESOS \O/   :)

"""**Test the detection with `IMAGES/<imagem>.jpg` image**"""

image_path   = "./IMAGES/etiqueta_3.jpg"
image = detect_image(yolo, image_path, "", input_size=YOLO_INPUT_SIZE, show=False, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(30,15))
plt.imshow(image)

image_path   = "./IMAGES/sample_4.jpeg"
image = detect_image(yolo, image_path, "", input_size=YOLO_INPUT_SIZE, show=False, CLASSES=TRAIN_CLASSES, rectangle_colors=(255,0,0))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(30,15))
plt.imshow(image)

"""# **You just trained your first Yolo v3 custom object detector on google colab, GOOD JOB!!**"""